### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Xscape
email: contact@xskape.io
description: Live stream lifes most amazing moments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xskape.io" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: jkol36
github_username:  jkol36
author: Jon Kolman
logo: assets/images/large-logo.png
twitter:
  username: jkol36
social:
  name: Jon Kolman
  links:
    - https://twitter.com/jkol36
    - https://www.facebook.com/jon-kolman
    - https://www.linkedin.com/in/jon-kolman
    - https://github.com/jkol36

languages: ["en"]
ampdir: amp

github: https://github.com/jkol36

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
